
name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: kavyagitopsacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t kavyagitopsacr.azurecr.io/kavya-app:${{github.sha}} .
          docker push kavyagitopsacr.azurecr.io/kavya-app:${{github.sha}}

      - name: Update GitOps repo
        run: |
            git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/kavya259/gitops-manifests.git
            cd gitops-manifests
            sed -i "s|image: .*|image: kavyagitopsacr.azurecr.io/kavya-app:${{github.sha}}|g" guestbook-ui-deployment.yaml
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add guestbook/guestbook-ui-deployment.yaml
            git commit -m "Update image ${{github.sha}}"
            git push
